---
Title: "Product Name Similarity Analysis By Category"
output: html_document
date: "2025-05-19"
---
```{r}
library(dplyr)
library(stringdist)
library(openxlsx)
library(fuzzyjoin)
library(data.table)
library(stringr)
library(future.apply)
library(progressr)
library(readxl)


有售商品_1P <- read_excel("C:/Users/Lily Peng/Downloads/有售商品_1P.xlsx")

有售商品_3P <- read_excel("C:/Users/Lily Peng/Downloads/有售商品_3P.xlsx")


df_有售商品_1P <- data.frame(有售商品_1P)
df_有售商品_3P <- data.frame(有售商品_3P) 


df_有售商品_1P$商品名稱 <- as.character(df_有售商品_1P$商品名稱)
df_有售商品_3P$商品名稱 <- as.character(df_有售商品_3P$商品名稱)

df_有售商品_1P$第一層 <- str_trim(df_有售商品_1P$第一層)
df_有售商品_3P$第一層 <- str_trim(df_有售商品_3P$第一層)


df_有售商品_1P$`部.課.NEW` <- str_trim(df_有售商品_1P$`部.課.NEW`)
df_有售商品_3P$`部.課.NEW` <- str_trim(df_有售商品_3P$`部.課.NEW`)


```


```{r}

# 啟用多核心與進度條
plan(multisession, workers = parallel::detectCores() - 1)
handlers("txtprogressbar")

start_time <- Sys.time()
all_matches <- list()

# 找出交集：同時出現在 1P 和 3P 中的 部.課.NEW + 第一層
common_keys <- intersect(
  unique(paste(df_有售商品_3P$`部.課.NEW`, df_有售商品_3P$第一層, sep = "___")),
  unique(paste(df_有售商品_1P$`部.課.NEW`, df_有售商品_1P$第一層, sep = "___"))
)

# 依據 部.課.NEW + 第一層 一一比對
for (key in common_keys) {
  key_parts <- strsplit(key, "___")[[1]]
  部課 <- key_parts[1]
  層級 <- key_parts[2]

  cat("🔍 比對部.課.NEW：", 部課, "｜第一層：", 層級, "\n")

  df_3P_layer <- df_有售商品_3P %>% filter(`部.課.NEW` == 部課, 第一層 == 層級)
  df_1P_layer <- df_有售商品_1P %>% filter(`部.課.NEW` == 部課, 第一層 == 層級)

  vec_new <- df_3P_layer$商品名稱
  vec_all <- df_1P_layer$商品名稱

  res <- with_progress({
    p <- progressor(along = vec_new)
    future_lapply(seq_along(vec_new), function(i) {
      p()
      dists <- stringdist(vec_new[i], vec_all, method = "jaccard")
      min_dist <- min(dists, na.rm = TRUE)
      if (min_dist <= 0.3) {
        idx <- which.min(dists)
        data.frame(
          原索引 = df_3P_layer$商品代碼[i],
          商品名稱_3P = vec_new[i],
          商品名稱_比對結果 = vec_all[idx],
          相似度 = 1 - min_dist,
          `部.課.NEW` = 部課,
          第一層 = 層級,
          stringsAsFactors = FALSE
        )
      } else {
        NULL
      }
    })
  })

  all_matches[[key]] <- do.call(rbind, res)
}

plan(sequential)
df_best_match <- do.call(rbind, all_matches)

# 合併原始 3P 商品資料
df_best_match <- df_有售商品_3P %>%
  right_join(df_best_match, by = c("商品代碼" = "原索引"))

# 顯示執行時間
end_time <- Sys.time()
cat("★ 總耗時：", round(as.numeric(difftime(end_time, start_time, units = "mins")), 1), "分鐘\n")

write.xlsx(df_best_match, "商品相似度分析_layer1.xlsx", overwrite = TRUE)

```



```{r}
df_best_match_1 <- df_best_match%>%
  left_join(df_有售商品_1P, by = c("商品名稱_比對結果" = "商品名稱", "第一層" = "第一層","部.課.NEW"="部.課.NEW"))
# :white_check_mark: **儲存結果到 Excel**
write.xlsx(df_best_match_1, "商品相似度分析_layer1.xlsx", overwrite = TRUE)
print(":white_check_mark: 商品相似度分析已完成，結果儲存至 '商品相似度分析.xlsx'！")
```

